apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: development
  source:
    path: manifests
    repoURL: https://github.com/dishults/dshults_argocd.git
  syncPolicy:
    automated:
      selfHeal: true
