Vagrant.configure("2") do |config|
	config.vm.box = "centos/stream8"
	config.vm.box_version = "20210210.0"
	config.vm.box_check_update = false
	config.vbguest.installer_options = { allow_kernel_upgrade: true } # impossible d'installer les add-ons virtual box sur le guest sans cette configuration

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

	config.vm.define 'ebenaissS' do |master|
		master.vm.hostname = 'ebenaissS'
		master.vm.network :private_network, ip: '192.168.42.110'
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		master.vm.provision "shell", privileged: true, path: "scripts/ebenaissS.sh", args: ['192.168.42.110']

		master.vm.provider "virtualbox" do |v|
			v.name = 'ebenaissS'
		end
	end
end
