Vagrant.configure("2") do |config|
	config.vm.box = "centos/stream8"
	config.vm.box_version = "20210210.0"
	config.vm.box_check_update = false

	config.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 4
		v.name = 'ebenaissS'
	end

	config.vm.define 'ebenaissS' do |master|
		master.vm.hostname = 'ebenaissS'
		master.vm.network :private_network, ip: '192.168.42.110'
		master.vm.provision "shell", privileged: true, path: "scripts/ebenaissS.sh", args: ['192.168.42.110']


	end
	config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4
end
