Vagrant.configure("2") do |config|
	config.vm.box = "centos/stream8"
	config.vm.box_version = "20210210.0"
	config.vm.box_check_update = false
	config.vbguest.installer_options = { allow_kernel_upgrade: true } # impossible d'installer les add-ons virtual box sur le guest sans cette configuration

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

	config.vm.define 'ebenaissS' do |master|
		master.vm.hostname = 'ebenaissS'
		master.vm.network :private_network, ip: '192.168.42.110'
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox" # répertoire partagé pour transmettre le token k3s
		master.vm.provision "shell", privileged: true, path: "scripts/ebenaissS.sh", args: ['192.168.42.110']

		master.vm.provider "virtualbox" do |v|
			v.name = 'ebenaissS'
		end
	end

	config.vm.define 'dshultsSW' do |worker|
		worker.vm.hostname = 'dshultsSW'
		worker.vm.network :private_network, ip: '192.168.42.111'
		worker.vm.synced_folder ".", "/vagrant", type: "virtualbox" # répertoire partagé pour transmettre le token k3s
		worker.vm.provision "shell", privileged: true, path: "scripts/dshultsSW.sh", args: ['192.168.42.110', '192.168.42.111']

		worker.vm.provider "virtualbox" do |v|
			v.name = 'dshultsSW'
		end
	end
end
## il faut potentiellement créer un fichier /etc/vbox/network.conf et y mettre : '* 192.168.42.0/24' sur le host
## il faut aussi potentiellement 'vagrant plugin install vagrant-vbguest' pour le répertoire partagé
