Vagrant.configure("2") do |config|
	config.vm.box = "centos/stream8"
	config.vm.box_version = "20210210.0"
	config.vm.box_check_update = false

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
		#v.customize ["modifyvm",: id, "--natdnsproxy1", "on"]
		#v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	end

	config.vm.define 'ebenaissS' do |master|
		master.vm.hostname = 'ebenaissS'
		master.vm.network :private_network, ip: '192.168.42.110'
		master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		master.vm.provision "shell", privileged: true, path: "scripts/ebenaissS.sh", args: ['192.168.42.110']

		master.vm.provider "virtualbox" do |v|
			v.name = 'ebenaissS'
		end
	end

	config.vm.define 'dshultsSW' do |worker|
		worker.vm.hostname = 'dshultsSW'
		worker.vm.network :private_network, ip: '192.168.42.111'
		worker.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"
		worker.vm.provision "shell", privileged: true, path: "scripts/dshultsSW.sh", args: ['192.168.42.110', '192.168.42.111']

		worker.vm.provider "virtualbox" do |v|
			v.name = 'dshultsSW'
		end
	end
end

## il faut potentiellement créer un fichier /etc/vbox/network.conf et y mettre : '* 192.168.42.0/24' sur le host
